### ISSUE TITLE
Socratic Seminar 21 Reading List (Dec 2023)

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [0xBEEFCAF3/bostonbitdevs#26]
Put links here!

**Comment by satsie** [comment]
Coinkite proposes a new way to do animated QR codes for Bitcoin (especially PSBT) https://bbqr.org

Currently the standard made by Blockchain Commons is the most widely used way to do animated QR codes https://x.com/christophera/status/1646273024650539008?s=46&t=PtDQpC8qXN6eLrhVrXTVNA

**Comment by john-light** [comment]
Missing sanctioned transactions detected
https://b10c.me/observations/08-missing-sanctioned-transactions/?t

Chun Wang (F2Pool cofounder) admits (in a since-deleted tweet) F2Pool is filtering sanctioned transactions 
https://twitter.com/OrangeSurfBTC/status/1727228792056471669

Wang later later announced (in a since-deleted tweet) that F2Pool is disabling the filter
https://twitter.com/ChrisBlec/status/1727380505635795370
