### ISSUE TITLE
Socratic Seminar 11 Reading List (December)

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#7]
Drop links here!

**Comment by satsie** [comment]
Topic: discuss the pros + cons of multiple implementations of bitcoin.

Reasoning: btcd broke again https://twitter.com/brqgoo/status/1587397646125260802?s=46&t=ees6gQ0q1gXw9i89Iv_TyQ

**Comment by satsie** [comment]
Topic No. 2: Full RBF

https://github.com/glozow/bitcoin-notes/blob/full-rbf/full-rbf.md

**Comment by edwargix** [comment]
> Topic No. 1: discuss the pros + cons of multiple implementations of bitcoin.
>
> Reasoning: btcd broke again https://twitter.com/brqgoo/status/1587397646125260802?s=46&t=ees6gQ0q1gXw9i89Iv_TyQ

This time around, projects other than btcd+lnd were affected because of an issue in older versions of rust-bitcoin.  This includes Liquid, which Burak himself is building products for:

- electrs: https://github.com/romanz/electrs/issues/783
- lightningdevkit: https://twitter.com/lightningdevkit/status/1587939344530145280
- liquid: https://twitter.com/Liquid_BTC/status/1587499305664913413
- mempool: https://twitter.com/glozow/status/1587403279470039046
- Greg Maxwell's thoughts re: a "Bitcoin spec": https://old.reddit.com/r/Bitcoin/comments/yj9low/lnd_emergency_bugfix_release_0154_beta/iuu1bw2/?context=3

**Comment by satsie** [comment]
wow! thank you for all that additional context @edwargix! This is going to make for a great conversation at the next BitDevs :rocket:
